### ISSUE TITLE
keys auth fails

### ISSUE THREAD

**Issue by BTBurke** [keys-pub/keysd#19]
`keys auth` fails with a password because the unlock request RPC is called with type UNKNOWN_AUTH instead of PASSWORD_AUTH.

Looks like the problem is here, because `Type` is not explicitly set when `AuthUnlockRequest` is created.

https://github.com/keys-pub/keysd/blob/a2a1183387edd59f8f4890feda7007e65419a1d6/service/cmd_auth.go#L77-L80

**Comment by gabriel** [comment]
Should be fixed in master now.

Yeah master was unstable because I've been debugging an issue with go plugins and modules (fido2+git libraries conflicting with each other).

But figured it out and master should be more stable now. I can't promise master won't be unstable in the future but I'll try not to break it.

**Comment by gabriel** [comment]
Thanks for reporting the issue though, is helpful :)
